apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/akhileshmishrabiz/k8sbootcamp-march26
    targetRevision: main
    path: eks-microservice-implementation/helm-ecommerce
    helm:
      releaseName: ecommerce
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
